#pragma config(Sensor, dgtl1,  fwheel,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  eyes,           sensorSONAR_cm)
#pragma config(Sensor, dgtl5,  ears,           sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  starter,        sensorTouch)
#pragma config(Sensor, dgtl8,  starter,        sensorTouch)
#pragma config(Motor,  port2,           left,          tmotorVex393, openLoop)
#pragma config(Motor,  port3,           right,         tmotorVex393, openLoop)
#pragma config(Motor,  port10,          front,         tmotorVex269, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void move_motors(int speed);
//function moves the motors
//parameter speed is the speed to move the motor
//	126 max for motor speed

task main()
{
		while(SensorValue(starter) == 0){
		}

	do{
		move_motors(60);
		wait1Msec(500);

		SensorValue(fwheel) = 0;

		while((SensorValue(eyes) >= 5) || (SensorValue(eyes) == -1)){
			//wait1Msec(500);
			move_motors(20);
		}

		move_motors(0);
		wait1Msec(500);

		while((SensorValue(eyes) < 5) || (SensorValue(eyes) == -1)){
			//wait1Msec(500);
			move_motors(-30);
			//wait1Msec(500);
		}

		move_motors(0);
	}while(true);
}

void move_motors(int speed){
	//motor[left] = -1 * speed;
	motor[right] = speed;

	return;
}
