#pragma config(Sensor, dgtl6,  SE,             sensorQuadEncoder)
#pragma config(Sensor, dgtl10, F1,             sensorTouch)
#pragma config(Sensor, dgtl11, F2,             sensorTouch)
#pragma config(Sensor, dgtl12, F3,             sensorTouch)
#pragma config(Sensor, dgtl5,  FF,         sensorTouch)
#pragma config(Sensor, dgtl4,  FU2,         sensorTouch)
#pragma config(Sensor, dgtl3,  FD2,         sensorTouch)
#pragma config(Sensor, dgtl2,  TF,         sensorTouch)
#pragma config(Motor,  port9,           rMotor,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void down(int distance);
void up(int distance);
int qu[3], qd[3];
int f1=0, f2=720, f3=1440;
int cFloor=0;
int distance=0;
bool upDown=false; //false is up true is down
task queue(){
	for(int k=0; k<3; k++){
		qu[k]=0;
		qd[k]=0;
	}
	do{
		if(SensorValue(F1)==1&&cFloor!=f1){
			qd[0]=1;
			if(cFloor==f2)
				upDown=true;
		}
		else if(SensorValue(F2)==1&&cFloor!=f2){
				qd[1]=1;
				qu[1]=1;
		}
		else if(SensorValue(F3)==1&&cFloor!=f3){
			qu[2]=1;
			if (cFloor==f2)
				upDown=false;
		}
		else if(SensorValue(FF)==1&&cFloor!=f1){
			qd[0]=1;
				if(cFloor==f2)
				upDown=true;
		}
		else if((SensorValue(FU2)==1||SensorValue(FD2)==1)&&cFloor!=f2){
				qd[1]=1;
				qu[1]=1;
		}
		else if(SensorValue(TF)==1&&cFloor!=f3){
			qu[2]=1;
			if (cFloor==f2)
				upDown=false;
		}
		EndTimeSlice();
	}while(true);
}
task main()
{
	StartTask (queue);
	do{
		SensorValue(SE)=0;
		if(upDown==false){ //that means the elevator is currently moving up
			if(qu[1]==1){
				distance=f2-cFloor;
				cFloor=f2;
				up(distance);
				qu[1]=0;
				qd[1]=0;
		}
			else if(qu[2]==1){
				distance=f3-cFloor;
				cFloor=f3;
				up(distance);
				upDown=true;
				qu[2]=0;
			}
		}
		else if(upDown==true){//elevator is moving down
			if(qd[1]==1){
				distance=f2-cFloor;
				cFloor=f2;
				down(distance);
				qd[1]=0;
				qu[1]=0;
			}
			else if(qd[0]==1){
				distance=f1-cFloor;
				cFloor=f1;
		    down(distance);
		    upDown=false;
		    qd[0]=0;
			}
		}
		EndTimeSlice();
	}while(true);
}
void up(int distance){
	while(-SensorValue(SE)<distance){
		motor[rMotor]=-63;
	}
	motor[rMotor]=0;
	wait1Msec(1000);
}
void down(int distance){
	while(-SensorValue(SE)>distance){
		motor[rMotor]=63;
	}
	motor[rMotor]=0;
	wait1Msec(1000);
}
