//#pragma config(Sensor, dgtl4,  led,            sensorDigitalOut)
#pragma config(Sensor, dgtl5,  led2,            sensorDigitalOut)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

//turnLEDOn[led];
//SensorValue[led] = 0;

SensorValue[led2] = 0;
wait1Msec(2000);

SensorValue[led2] = 1;
wait1Msec(2000);

/*SensorValue[led2] = 1;
wait1Msec(1000);
SensorValue[led] = 1;
SensorValue[led2] = 0;*/
}
