#pragma config(Sensor, dgtl6,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl10,  touchSensor1,         sensorTouch)//sensor for floor 1 is on digital 6
#pragma config(Sensor, dgtl11,  touchSensor2,         sensorTouch)//sensor for floor 2 is on digital 7
#pragma config(Sensor, dgtl12,  touchSensor3,         sensorTouch)//sensor for floor 3 is on digital 8
#pragma config(Motor,  port9,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void up (int floorDis);//for going up
void down (int floorDis);//for going down

const int f1=0;
const int f2=720;
const int f3=1440;

task main()
{
	wait1Msec(0);
	int distance=0;//distance to travel
	int cFloor=f1;//current floor is floor 1 to start
	do{
			if(SensorValue[touchSensor1]==1)
				distance=f1-cFloor;
			else if(SensorValue[touchSensor2]==1)
				distance=f2-cFloor;
			else if(SensorValue[touchSensor3]==1)
				distance=f3-cFloor;
			if(distance < 0)
				down(distance);
			else
				up(distance);



}while(1);

}
void down(int floorDis){
	SensorValue[rightEncoder] = 0;	  // Set the encoder so that it starts counting at 0
	while(-SensorValue[rightEncoder]>floorDis)
		motor[rightMotor]=63;
	motor[rightMotor]=0;
}
void up(int floorDis){
	SensorValue[rightEncoder] = 0;	  // Set the encoder so that it starts counting at 0
	while(-SensorValue[rightEncoder]<floorDis)
		motor[rightMotor]=-63;
	motor[rightMotor]=0;
}
