#pragma config(Sensor, dgtl6,  shaft_1,        sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  top_lever,      sensorTouch)
#pragma config(Sensor, dgtl9,  bottom_lever,   sensorTouch)
#pragma config(Sensor, dgtl10, floor_1,        sensorTouch)
#pragma config(Sensor, dgtl11, floor_2,        sensorTouch)
#pragma config(Sensor, dgtl12, floor_3,        sensorTouch)
#pragma config(Motor,  port8,  left_motor,     tmotorVex393, openLoop)
#pragma config(Motor,  port9, right_motor,    tmotorVex393, openLoop)

//*!!Code generated by that awesome team              !!*//

void move_to_bottom();
//function moves the elevator to the bottom floor
//takes no parameters

void move_to_top();
//function moves the elevator to the top floor
//takes no parameters

void move_to_middle();
//function moves the elevator to the middle floor
//takes no parameters

bool elevator_in_position();
//function goes to the bottom floor if not already in position
//function takes no parameters

void move_motors(int speed);
//function moves the motors
//parameter speed is the speed to move the motor
//	126 max for motor speed

typedef enum{
	FIRST = 0,
	SECOND = 800,
	THIRD = 1600,
} floors;

typedef enum{
	UP = 1,
	DOWN = -1,
} direction;

task main()
{
	int user_input, current_floor;

	move_to_bottom();

	wait1Msec(2000);

	if(SensorValue(floor_1) == 1)
		int x = 1;

	move_motors(0);
}

bool elevator_in_position(){
	if((SensorValue(top_lever) == 0) && (SensorValue(bottom_lever) == 0))
		return false;

	else if((SensorValue(top_lever) == 0) && (SensorValue(bottom_lever) == 1))
		return true;

	else
		return false;
}

void move_motors(int speed){
	motor[left_motor] = speed;
	motor[right_motor] = -1 * speed;

	return;
}

void move_to_bottom(){
	while(elevator_in_position() == false){
		move_motors(50);

		if(SensorValue(bottom_lever) == 1)
			move_motors(0);
	}

	SensorValue[shaft_1] = 0;
}

void move_to_top(){
	while(elevator_in_position() == false){
		move_motors(50);

		if(SensorValue(bottom_lever) == 0)
			move_motors(0);
	}

	SensorValue[shaft_1] = 0;
}

int check_floor(int user_floor, int current_floor){
	if((user_floor - current_floor) > 0)//moves down a floor
		return 1;

	else if((user_floor - current_floor) == 0)//if moves to same floor
		return 0;

	else if((user_floor - current_floor) < 0)//moves up a floor
		return -1;

	else
		return 0;
}

int check_floor(int shaft_distance){
	if(SensorValue[shaft_1] == THIRD)
		return 3;

	else if(SensorValue[shaft_1] == SECOND)// && SensorValue[shaft_1] > floors.FIRST){
		return 2;

	else if(SensorValue[shaft_1] == FIRST)
		return 1;

	else
		return 0;
}
