#pragma config(Sensor, dgtl1,  top_lever,      sensorTouch)
#pragma config(Motor,  port2,           top_right,     tmotorVex269, openLoop)//, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	bool reached_top = false;

	do{
		motor[top_right] = 126;

		if(SensorValue(top_lever) == 1){
			reached_top = true;
			motor[top_right] = 0;
		}

	}while(reached_top == false);

	return;
}
