#pragma config(Sensor, dgtl3,  terror_switch,  sensorTouch)
#pragma config(Sensor, dgtl4,  green,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl5,  yellow,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  shaft_1,        sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  top_lever,      sensorTouch)
#pragma config(Sensor, dgtl9,  bottom_lever,   sensorTouch)
#pragma config(Sensor, dgtl10, floor_1,        sensorTouch)
#pragma config(Sensor, dgtl11, floor_2,        sensorTouch)
#pragma config(Sensor, dgtl12, floor_3,        sensorTouch)
#pragma config(Motor,  port8,  left_motor,     tmotorVex393, openLoop)
#pragma config(Motor,  port9,  right_motor,    tmotorVex393, openLoop)

//*!!Code generated by that awesome team              !!*//

bool terror_accomplished();
//function stops if the kill switch is hit
//takes no parameters

bool elevator_in_position();
//function goes to the bottom floor if not already in position
//function takes no parameters

//void stop_all_motors();
//stops motors in digitial ports
//takes no parameters

void move_motors(int speed);
//function moves the motors
//parameter speed is the speed to move the motor
//	126 max for motor speed

task main()
{
	//turnLEDOn(LED);

	//wait10Msec(1000);

	while(elevator_in_position() == false){
		move_motors(50);

		if(SensorValue(bottom_lever) == 1){
			//elevator_in_position() = true;
			move_motors(0);
		}
	}


	wait1Msec(2000);

	do{
		if(SensorValue(top_lever) == 1){
			while((SensorValue(bottom_lever) == 0)){// && (SensorValue(bottom_lever) == 0)){
				move_motors(30);
			}
		}

		if(SensorValue(bottom_lever) == 1){
			while((SensorValue(top_lever) == 0)){// && (SensorValue(top_lever) == 0)){
				move_motors(-30);
			}
		}
	}while(terror_accomplished() == false);

	move_motors(0);

	return;
}

bool terror_accomplished(){
	if(SensorValue(terror_switch) == 1){
		return true;
	}

	else{
		return false;
	}
}

/*void stop_all_motors(){
	//move_motors(0);
	//motor[small] = 0;
	//motor[med] = 0;

	return;
}*/

bool elevator_in_position(){
	if((SensorValue(top_lever) == 0) && (SensorValue(bottom_lever) == 0)){
		return false;
	}

	else if((SensorValue(top_lever) == 0) && (SensorValue(bottom_lever) == 1)){
		return true;
	}

	else{
		return false;
	}
}

void move_motors(int speed){
	motor[left_motor] = speed;
	motor[right_motor] = -1 * speed;

	return;
}
