#pragma config(Sensor, dgtl6,  SE,             sensorQuadEncoder)
#pragma config(Sensor, dgtl10, F1,             sensorTouch)
#pragma config(Sensor, dgtl11, F2,             sensorTouch)
#pragma config(Sensor, dgtl12, F3,             sensorTouch)
#pragma config(Sensor, dgtl5,  FF,         sensorTouch)
#pragma config(Sensor, dgtl4,  FU2,         sensorTouch)
#pragma config(Sensor, dgtl3,  FD2,         sensorTouch)
#pragma config(Sensor, dgtl2,  TF,         sensorTouch)
#pragma config(Motor,  port9,           rMotor,        tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void down(int distance);
void up(int distance);
void move(int fff);
//void queue(int qu, int qd);

int qu[10], qd[10];
int f1=0, f2=720, f3=1440;
int cFloor=0;
int distance=0;
bool dir=true; // boolean for knowing whether the elevator is going up currently or not
//true=up false=down


task queue(){
	//filling the array with 0's
	for (int k=0; k<10; k++){
		qu[k]=0;
		qd[k]=0;
	}
	int i=0;
	while(true){
		if(SensorValue(F1)==1){
	    qd[i]=1;
	    i++;
		}
		if(SensorValue(F2)==1){
		distance=f2-cFloor;
			if(distance<0)
				qd[i]=2;
			else
				qu[i]=2;
			i++;
		}
		if(SensorValue(F3)==1){
			qu[i]=3;
			i++;
		}
		if(SensorValue(FF)==1){
	   	qd[i]=1;
	   	i++;
		}
		if(SensorValue(FU2)==1||SensorValue(FD2)==1){
			if(distance<0)
				qd[i]=2;
			else
				qu[i]=2;
			i++;
		}
		if(SensorValue(TF)==1){
			qu[i]=3;
			i++;
		}
	}
	EndTimeSlice();

}

task main()
{
	int floornum=0;
	StartTask (queue);
	do{
			if(dir==true){
		for(int y=0; y<10; y++){
			floornum=qu[y];
			move(floornum);
		}
	}
		if(dir==false){
		for(int r=0; r<10; r++){
			floornum=qd[r];
			move(floornum);
		}
	}
	}while(true);
}

void move(int fff){
	SensorValue(SE)=0;
		if(fff==1){
			distance=f1-cFloor;
			dir=true;
	    down(distance);
	    cFloor=f1;
		}
		if(fff==2){
			distance=f2-cFloor;
			if(distance<0){
				dir=false;
				down(distance);
			}
			else{
				dir=true;
				up(distance);
			}
			cFloor=f2;
		}
		if(fff==3){
			dir=true;
			distance=f3-cFloor;
			up(distance);
			cFloor=f3;
		}
		/*
		if(SensorValue(FF)==1){
			distance=f1-cFloor;
			dir=false;
	    down(distance);
	    cFloor=f1;
		}
		if(SensorValue(FU2)==1||SensorValue(FD2)==1){
			distance=f2-cFloor;
			if(distance<0){
				dir=false;
				down(distance);
			}
			else{
				dir=true;
				up(distance);
			}
			cFloor=f2;
		}
		if(SensorValue(TF)==1){
			distance=f3-cFloor;
			dir=false;
			up(distance);
			cFloor=f3;
		}
		*/
		EndTimeSlice();
}


void up(int distance){
	while(-SensorValue(SE)<distance){
		motor[rMotor]=-63;
	}
	motor[rMotor]=0;
}

void down(int distance){
	while(-SensorValue(SE)>distance){
		motor[rMotor]=63;
	}
	motor[rMotor]=0;
}
